### ISSUE TITLE
Very Nice Work. I have a question about Colab

### ISSUE THREAD

**Issue by yifeipet** [beresandras/gan-flavours-keras#1]
Hello Andras,
Thank you for your hard work! I am surprised to see the basic GAN loss outperforms other advanced GAN losses. But Colab gives me error when finishing the first epoch:
FileNotFoundError: [Errno 2] No such file or directory: 'images/0_10_2.971.png'. 

Can you let me know how to fix the issue?
Thank you!

Sincerely,
Yifei

**Comment by beresandras** [comment]
Hi! The issue was that it tried to save visualizations into a non-existing folder. I fixed it so that now it shows the images instead when using Colab. Let me know if you have any other issues!

**Comment by yifeipet** [comment]
Thank you, Andras! I learned a lot from your codes than my self-study of two years.
